name = "CTSolvers"
uuid = "d3e8d392-8e4b-4d9b-8e92-d7d4e3650ef6"
version = "0.1.0"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]

[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
CTDirect = "790bbbee-bee9-49ee-8912-a9de031322d5"
CTModels = "34c4fa32-2049-4079-8329-de33c2a22e2d"
CTParser = "32681960-a1b1-40db-9bff-a1ca817385d1"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"

[weakdeps]
MadNCL = "434a0bcb-5a7c-42b2-a9d3-9e3f760e7af0"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPMumps = "3b83494e-c0a4-4895-918b-9157a7a085a1"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NLPModelsKnitro = "bec4dd0d-7755-52d5-9a02-22f0ffc7efcb"

[extensions]
CTSolversIpopt = "NLPModelsIpopt"
CTSolversKnitro = "NLPModelsKnitro"
CTSolversMadNCL = ["MadNCL", "MadNLP", "MadNLPMumps"]
CTSolversMadNLP = ["MadNLP", "MadNLPMumps"]

[compat]
ADNLPModels = "0.8"
CTBase = "0.16"
CTDirect = "0.17"
CTModels = "0.6"
CTParser = "0.7.1"
CommonSolve = "0.2"
DocStringExtensions = "0.9"
ExaModels = "0.9"
KernelAbstractions = "0.9"
MLStyle = "0.4"
MadNCL = "0.1"
MadNLP = "0.8"
MadNLPMumps = "0.5"
NLPModels = "0.21"
NLPModelsIpopt = "0.11"
NLPModelsKnitro = "0.10"
SolverCore = "0.3"
julia = "1.10"
